version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: jasmcdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "./wait-for-db.sh &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=jasmc.settings
      - DEBUG=1
      - DB_NAME=jasmcdb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
  populate:
    build: .
    command: >
      sh -c "./wait-for-db.sh &&
             python manage.py populate_posts"
    volumes:
      - .:/app
    depends_on:
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=jasmc.settings
      - DEBUG=1
      - DB_NAME=jasmcdb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
