name: Terraform, ECR Push

on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    outputs:
      ecr_frontend_repo_url: ${{ steps.get-output.outputs.ecr_frontend_repo_url }}
      ecr_backend_repo_url: ${{ steps.get-output.outputs.ecr_backend_repo_url }}

    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: "false"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan

      - name: Extract ECR Repository URL
        id: get-output
        run: |
          ECR_FRONTEND_REPO=$(terraform output -raw ecr_frontend_repo_url)
          echo "ecr_frontend_repo_url=$ECR_FRONTEND_REPO" >> $GITHUB_OUTPUT
          ECR_BACKEND_REPO=$(terraform output -raw ecr_backend_repo_url)
          echo "ecr_backend_repo_url=$ECR_BACKEND_REPO" >> $GITHUB_OUTPUT

  docker:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - run: echo "ECR repo is ${{ needs.terraform.outputs.ecr_repo }}"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Frontend & Backend
        env:
          ECR_FRONTEND_REPO_URL: ${{ needs.terraform.outputs.ecr_frontend_repo_url }}
          ECR_BACKEND_REPO_URL: ${{ needs.terraform.outputs.ecr_backend_repo_url }}
        run: |
          FRONTEND_IMAGE_URI="$ECR_FRONTEND_REPO_URL:latest"
          BACKEND_IMAGE_URI="$ECR_BACKEND_REPO_URL:latest"

          docker build -t $FRONTEND_IMAGE_URI ./frontend
          docker push $FRONTEND_IMAGE_URI
          docker build -t $BACKEND_IMAGE_URI ./backend
          docker push $BACKEND_IMAGE_URI
