name: Terraform, ECR Push

on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    outputs:
      ecr_frontend_repo_url: ${{ steps.get-output.outputs.ecr_frontend_repo_url }}
      ecr_backend_repo_url: ${{ steps.get-output.outputs.ecr_backend_repo_url }}
      eks_cluster_name: ${{ steps.get-output.outputs.eks_cluster_name }}

    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: "false"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        id: get-output
        run: |
          ECR_FRONTEND_REPO=$(terraform output -raw ecr_frontend_repo_url)
          echo "ecr_frontend_repo_url=$ECR_FRONTEND_REPO" >> $GITHUB_OUTPUT

          ECR_BACKEND_REPO=$(terraform output -raw ecr_backend_repo_url)
          echo "ecr_backend_repo_url=$ECR_BACKEND_REPO" >> $GITHUB_OUTPUT

          EKS_CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
          echo "eks_cluster_name=$EKS_CLUSTER_NAME" >> $GITHUB_OUTPUT

  kubectl:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ needs.terraform.outputs.eks_cluster_name }}

      - name: Build, Push and Deploy with Skaffold
        env:
          FRONTEND_IMAGE_NAME: ${{ needs.terraform.outputs.ecr_frontend_repo_url }}
          BACKEND_IMAGE_NAME: ${{ needs.terraform.outputs.ecr_backend_repo_url }}
        run: |
          skaffold run -f skaffold.pipeline.yaml
